sudo: required
language: go
services:
- docker
go:
- "1.11.x"
env:
  global:
  - TERRAFORM_VERSION=0.11.8
  - KUBECTL_VERSION=v1.11.2
  # Key for Gcloud Service account (decrypted in before_install)
  - TF_VAR_gcloud_creds=./google-account.json
  - TF_VAR_image_repo=us.gcr.io/usermirror-staging/config-api

before_install:
- curl -L https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip | funzip >test/terraform
- curl -L https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl >kubectl
- sudo install ./kubectl ./test/terraform /usr/local/bin
- openssl aes-256-cbc -K ${encrypted_c579a9585696_key} -iv ${encrypted_c579a9585696_iv} -in ./test/usermirror-staging.json -out ${TF_VAR_gcloud_creds} -d

install:
- (cd terraform/gcp && terraform init)
- make docker-build

before_script:
- (cd terraform/gcp && TF_VAR_image_tag=${TRAVIS_COMMIT} terraform plan)
- make gcr-push

script:
- (cd terraform/gcp && TF_VAR_image_tag=${TRAVIS_COMMIT} terraform apply -auto-approve)

after_script:
- (cd terraform/gcp && TF_VAR_image_tag=${TRAVIS_COMMIT} terraform destroy -auto-approve)
