apiVersion: v1
kind: Service
metadata:
  name: embed-config-api
  labels:
    app: embed-config-api
spec:
  type: LoadBalancer
  ports:
  - name: embed-config
    targetPort: 8888
    port: 80
  selector:
    app: embed-config-api
